USE inspire;
SHOW TABLES;

-- 1
SELECT DEPARTMENT_NAME '학과 명', CATEGORY '계열'
FROM tb_department;

-- 2
SELECT CONCAT(DEPARTMENT_NAME, '의 정원은 ', CAPACITY, '명 입니다.') '학과별 정원'
FROM tb_department;

-- 3
SELECT STUDENT_NAME 
FROM tb_student
WHERE ABSENCE_YN = 'Y' 
AND DEPARTMENT_NO = (
	SELECT DEPARTMENT_NO 
	FROM tb_department 
	WHERE DEPARTMENT_NAME = '국어국문학과'
)
AND STUDENT_SSN LIKE '%-2%';

-- 4
SELECT STUDENT_NAME FROM tb_student
WHERE STUDENT_NO
IN('A513079', 'A513090', 'A513091', 'A513110', 'A513119');

--5
SELECT DEPARTMENT_NAME, CATEGORY
FROM tb_department
WHERE CAPACITY BETWEEN 20 AND 30;

-- 6
SELECT PROFESSOR_NAME
FROM tb_professor
WHERE DEPARTMENT_NO IS NULL;

-- 7
SELECT *
FROM tb_student
WHERE DEPARTMENT_NO IS NULL;

-- 8
SELECT CLASS_NO
FROM tb_class
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

-- 9
SELECT DISTINCT CATEGORY
FROM tb_department;

-- 10
SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN
FROM tb_student
WHERE ENTRANCE_DATE LIKE '2002-%'
AND ABSENCE_YN = 'N'
AND STUDENT_ADDRESS LIKE '전주시%';




